-- File auto generated by purescript-bridge! --
module Servant.Subscriber.Types where

import Prim (Array, String)

import Data.Generic (class Generic)


data Path =
    Path (Array String)

derive instance genericPath :: Generic Path

